### ISSUE TITLE
Задачи

### ISSUE THREAD

**Issue by RemiZOffAlex** [idovgalyov-4xxi/PandemicBoardGame#12]
- Нет описания
- Нет точки входа
- Какой фреймворк ляжет в основу бекенда? (рекомендую Flask)
- Нет каталогов для разделения фронт части от бека. Если будет фреймворк, то возможно разделение не потребуется, т.к. страницы будут генерироваться через шаблонизатор самим беком
- Какой API будет в основе (рекомендую JSON-RPC)
- Где Vue?

**Comment by submaps** [comment]
Спасибо за комментарии, исправим

**Comment by idovgalyov-4xxi** [comment]
@RemiZOffAlex , привет!

Спасибо за комментарии! По основной части комментариев будет отмечено следующее: браузерная версия является лишь одним из конечных вариантов игры (по первоначальной задумке приложение имело только десктопную версию, впоследствии было решено прорабатывать параллельно разные варианты).
- Документация к проекту ожидается при первом релизе, сейчас над ней ведётся работа.
- С entrypoint-ом аналогично, появится в первой рабочей версии, тут без него никуда.
- Про веб-фреймворки пока мало дискуссий в силу сказанного выше. Для браузерной версии мы скорее всего, действительно, остановимся на выборе Flask как более знакомого нам.
- API точно будет относиться к JSON-у. Будет ли это собственный формат или что-то из готового, пока обсуждается.
- Со всем, что касается web-frontend части, лучше обращаться к @submaps, пока что работы по фронту и бэку ведутся раздельно, как-то совмещать будем уже в будущем.

**Comment by D-Mantrid** [comment]
Closed as obsolete due to [project migration](https://github.com/Discarded-Team/Pyndemic).
