### ISSUE TITLE
Не рекомендую ini подобный конфиг

### ISSUE THREAD

**Issue by RemiZOffAlex** [idovgalyov-4xxi/PandemicBoardGame#13]
Недостатки:

- Нет полноценных структур типа словарь
- Нет полноценных структур типа список
- Для добавления элемента в список, словарь и др. требуется полная перезагрузка приложения
- Чрезмерный размер файла и его запутанность при увеличении количества разделов

Рекомендую json, yaml или даже непосредственно config.py. Динамически добавляемые данные лучше держать в базе данных

**Comment by idovgalyov-4xxi** [comment]
Спасибо за рекомендацию!
INI-формат сейчас для нас прежде всего удобен как более читабельный, и его так же легко парсить или менять внутренними средствами Python, как тот же JSON или YAML.

Вообще, у нас не было ставки на то, что приложение будет работать без перезапуска подобно серверу, да и целом мы были намерены как раз держать такой формат для хранения _не очень большого числа_ тех параметров, которые разрешено изменять между игровыми сессиями вручную.

Поэтому серьёзных причин отказаться от его использования в ближайшей перспективе мы пока не видим.
Хотя в разделении параметров по разным файлам по критериям изменяемости и отношения к геймплею есть смысл, и мы намерены однажды так сделать.
