### ISSUE TITLE
Создать пакет бека

### ISSUE THREAD

**Issue by RemiZOffAlex** [idovgalyov-4xxi/PandemicBoardGame#14]
Все файлы py необходимо убрать внутрь пакета. Снаружи оставить только запускающий файл

**Comment by idovgalyov-4xxi** [comment]
Текущая структура проекта осталась в наследство от предыдущего владельца и для удобства не изменялась. К ближайшему релизу (0.1) планируется привести структуру файлов к стандартному виду.

**Comment by idovgalyov-4xxi** [comment]
Реализовано в 39f1714607cf675a41b4f796399740d4274b23c2.
