### ISSUE TITLE
Версия Python

### ISSUE THREAD

**Issue by RemiZOffAlex** [idovgalyov-4xxi/PandemicBoardGame#15]
Нужно определиться с версией Python. Актуальна на данный момент третья версия. Для третьей версии явное указание кодировки   

`# coding: utf-8`

не требуется.

**Comment by idovgalyov-4xxi** [comment]
Ещё раз привет :v:
Весь код пишется под Python 3. Эта инструкция в принципе ничему не мешает, так что вопросы, связанные с ней, мы относим к совсем второстепенным.
